// <auto-generated />
using Laba5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laba5.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250301001834_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laba17.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Высокопроизводительный ноутбук с 16 ГБ оперативной памяти и SSD на 512 ГБ",
                            Name = "Ноутбук",
                            Price = 999.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Последняя модель смартфона с 128 ГБ встроенной памяти",
                            Name = "Смартфон",
                            Price = 499.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Description = "10-дюймовый планшет с 64 ГБ встроенной памяти",
                            Name = "Планшет",
                            Price = 299.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Description = "Умные часы с монитором сердечного ритма и GPS",
                            Name = "Умные часы",
                            Price = 199.99m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
